### ISSUE TITLE
Backend Todo

### ISSUE THREAD

**Issue by jordanmckoy** [jordanmckoy/Sylla#19]
- [ ] Create a way to submit requests to the bot and get responses from the bot. It should store the history.
- [ ] Design Database Schema
- [ ] Use NLP to detect intent of message to use as a prefilter
- [ ] Design a system message to allow ChatGPT to become better at the task at hand
- [ ] Implement Auth and session handling
- [ ] Get the bot to guide them towards answers
